remote_theme: pages-themes/minimal

title: My Economics Blog

description: Short articles, reviews, and insights.

google_analytics: 

show_downloads: false
layout: default



# Navigation Links

nav_links:

  - title: Home

    url: /

  - title: Portfolio

    url: https://alisyedshujaat.github.io/

  - title: LinkedIn

    url: https://www.linkedin.com/in/your-profile///www.linkedin.com/in/your-profile/
